/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface':                  '#131313',
        'surface-dim':              '#131313',
        'surface-bright':           '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low':    '#1c1b1b',
        'surface-container':        '#201f1f',
        'surface-container-high':   '#2a2a2a',
        'surface-container-highest':'#353534',
        'surface-variant':          '#353534',
        'on-surface':               '#e5e2e1',
        'on-surface-variant':       '#bcc9cd',
        'background':               '#131313',
        'on-background':            '#e5e2e1',
        'primary':                  '#4cd7f6',
        'primary-container':        '#06b6d4',
        'primary-fixed':            '#acedff',
        'primary-fixed-dim':        '#4cd7f6',
        'on-primary':               '#003640',
        'on-primary-container':     '#00424f',
        'on-primary-fixed':         '#001f26',
        'on-primary-fixed-variant': '#004e5c',
        'inverse-primary':          '#00687a',
        'secondary':                '#a1cedb',
        'secondary-container':      '#1e4d58',
        'secondary-fixed':          '#bceaf7',
        'secondary-fixed-dim':      '#a1cedb',
        'on-secondary':             '#003640',
        'on-secondary-container':   '#90bcc9',
        'on-secondary-fixed':       '#001f26',
        'on-secondary-fixed-variant':'#1e4d58',
        'tertiary':                 '#ffb873',
        'tertiary-container':       '#e89337',
        'tertiary-fixed':           '#ffdcbf',
        'tertiary-fixed-dim':       '#ffb873',
        'on-tertiary':              '#4b2800',
        'on-tertiary-container':    '#5b3200',
        'on-tertiary-fixed':        '#2d1600',
        'on-tertiary-fixed-variant':'#6a3b00',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'on-error-container':       '#ffdad6',
        'outline':                  '#869397',
        'outline-variant':          '#3d494c',
        'surface-tint':             '#4cd7f6',
        'inverse-surface':          '#e5e2e1',
        'inverse-on-surface':       '#313030',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
